MvcKutuphaneProje/Controllers/DuyuruController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphaneProje.Models.Entity;

namespace MvcKutuphaneProje.Controllers
{
    public class DuyuruController : Controller
    {
        // GET: Duyuru
        DB_KutuphaneEntities db = new DB_KutuphaneEntities();
        public ActionResult Index()
        {
            var degerler = db.TBL_DUYURULAR.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult DuyuruEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DuyuruEkle(TBL_DUYURULAR p)
        {
            db.TBL_DUYURULAR.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruGetir(TBL_DUYURULAR p)
        {
            var duyuru = db.TBL_DUYURULAR.Find(p.ID);
            return View("DuyuruGetir",duyuru);
        }
        public ActionResult DuyuruGuncelle(TBL_DUYURULAR t)
        {
            var duyuru = db.TBL_DUYURULAR.Find(t.ID);
            duyuru.KATEGORI = t.KATEGORI;
            duyuru.TARIH = t.TARIH;
            duyuru.ICERIK = t.ICERIK;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Duyurusil(int id)
        {
            var silinecek = db.TBL_DUYURULAR.Find(id);
            db.TBL_DUYURULAR.Remove(silinecek);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphaneProje/Views/Duyuru/DuyuruEkle.cshtml
@model MvcKutuphaneProje.Models.Entity.TBL_DUYURULAR
@{
    ViewBag.Title = "DuyuruEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div style="margin-bottom:15px; margin-top:15px">
        <label>Duyuru Kategorisi</label>
        @Html.TextBoxFor(k => k.KATEGORI, new { @class = "Form-Control" })
    </div>
    <div style="margin-bottom:15px; margin-top:15px">
        <label>Duyuru İçerik</label>
        @Html.TextBoxFor(k => k.ICERIK, new { @class = "Form-Control" })
    </div>
    <div style="margin-bottom:15px; margin-top:15px">
        <label>Duyuru Tarihi</label>
        @Html.TextBoxFor(k => k.TARIH, new { @class = "Form-Control" })
    </div>
    <button class="btn btn-success" style="background-color:green; color:white">Kaydet</button>
    <a href="/Duyuru/Index/" class="btn btn-danger" style="background-color:red; color:white">İptal</a>
</form>

MvcKutuphaneProje/Views/Duyuru/DuyuruGetir.cshtml
@model MvcKutuphaneProje.Models.Entity.TBL_DUYURULAR
@{
    ViewBag.Title = "DuyuruGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("DuyuruGuncelle", "Duyuru", FormMethod.Post))
{
    <div class="form-group" style="margin-top:20px">
        <label>Duyuru No</label>
        @Html.TextBoxFor(x => x.ID, new { @class = "Form-Control", @readonly = "readonly" })
        <br />
        <label>Duyuru Kategori</label>
        @Html.TextBoxFor(x => x.KATEGORI, new { @class = "Form-Control" })
        <br />
        <label>Duyuru İçerik</label>
        @Html.TextAreaFor(x => x.ICERIK, new { @class = "Form-Control" })
        <br />
        <label>Duyuru Tarihi</label>
        @Html.TextBoxFor(x => x.TARIH, new { @class = "Form-Control" })
    </div>
    <div>
        <button class="btn btn-warning" style="background-color:orangered; color:white">Güncelle</button>
        <a href="/Duyuru/Index/" class="btn btn-danger" style="background-color:red; color:white">İptal</a>

    </div>
}

MvcKutuphaneProje/Views/Duyuru/Index.cshtml
@using MvcKutuphaneProje.Models.Entity
@model List<TBL_DUYURULAR>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2 style="text-align:center; margin-bottom:20px; color:red">Duyuru Listesi</h2>
<table class="table table-bordered">
    <tr>
        <th>DUYURU NO</th>
        <th>KATEGORİ</th>
        <th>TARİH</th>
        <th>SİL</th>
        <th>İÇERİK</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.ID</td>
            <td>@x.KATEGORI</td>
            <td>@Convert.ToDateTime(x.TARIH).ToString("dd/MM/yyyy")</td>
            <td><a href="/Duyuru/Duyurusil/@x.ID" style="background-color:red; color:white" class="btn btn-danger">Sil</a></td>
            <td><a href="/Duyuru/DuyuruGetir/@x.ID" style="background-color:indigo; color:white" class="btn btn-default">İçerik</a></td>

        </tr>
    }
</table>
<a href="/Duyuru/DuyuruEkle" style="background-color:dodgerblue; color:white" class="btn btn-primary">Duyuru Ekle</a>