MvcKutuphaneProje/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Security.Cryptography.Pkcs;
using System.Web;
using System.Web.Mvc;
using MvcKutuphaneProje.Models.Entity;
namespace MvcKutuphaneProje.Controllers
{
    public class KitapController : Controller
    {
        // GET: Kitap
        DB_KutuphaneEntities db = new DB_KutuphaneEntities();
        public ActionResult Index(string p)
        {
            var kitaplar = from k in db.TBL_KITAPLAR select k;
            if (!string.IsNullOrEmpty(p))
            {
                kitaplar = kitaplar.Where(m => m.AD.Contains(p));
            }
            return View(kitaplar.ToList());
        }
        [HttpGet]
        public ActionResult KitapEkle()
        {
            List<SelectListItem> deger1 = (from i in db.TBL_KATEGORILER.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.AD,
                                               Value = i.ID.ToString()
                                           }).ToList();
            List<SelectListItem> deger2 = (from i in db.TBL_YAZARLAR.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.AD + ' ' + i.SOYAD,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            return View();
        }
        [HttpPost]
        public ActionResult KitapEkle(TBL_KITAPLAR k)
        {
            var ktg = db.TBL_KATEGORILER.Where(x => x.ID == k.TBL_KATEGORILER.ID).FirstOrDefault();
            var yzr = db.TBL_YAZARLAR.Where(x => x.ID == k.TBL_YAZARLAR.ID).FirstOrDefault();
            k.TBL_KATEGORILER = ktg;
            k.TBL_YAZARLAR = yzr;
            db.TBL_KITAPLAR.Add(k);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KitapSil(int id)
        {
            var sil = db.TBL_KITAPLAR.Find(id);
            db.TBL_KITAPLAR.Remove(sil);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KitapGetir(int id)
        {
            var ktp = db.TBL_KITAPLAR.Find(id);
            List<SelectListItem> deger1 = (from i in db.TBL_KATEGORILER.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.AD,
                                               Value = i.ID.ToString()
                                           }).ToList();
            List<SelectListItem> deger2 = (from i in db.TBL_YAZARLAR.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.AD + ' ' + i.SOYAD,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            return View("KitapGetir", ktp);
        }
        public ActionResult KitapGuncelle(TBL_KITAPLAR k)
        {
            var kitap = db.TBL_KITAPLAR.Find(k.ID);
            kitap.AD = k.AD;
            kitap.BASIMYIL = k.BASIMYIL;
            kitap.SAYFA = k.SAYFA;
            kitap.YAYINEVI = k.YAYINEVI;
            k.DURUM = true;
            var ktg = db.TBL_KATEGORILER.Where(x => x.ID == k.TBL_KATEGORILER.ID).FirstOrDefault();
            var yzr = db.TBL_YAZARLAR.Where(x => x.ID == k.TBL_YAZARLAR.ID).FirstOrDefault();
            kitap.KATEGORI = ktg.ID;
            kitap.YAZAR = yzr.ID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphaneProje/Views/Kitap/Index.cshtml
@using MvcKutuphaneProje.Models.Entity
@model List<TBL_KITAPLAR>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2 style="text-align:center; color:red">Kitap Listesi</h2>

@using (Html.BeginForm("Index", "Kitap", FormMethod.Get))
{
    <div style="margin-bottom:20px; margin-top:20px; background-color:gray">
        <table class="table table-bordered">
            <tr>
                <td>
                    <b style="color:#160ed0">Aranacak Kitabı Girin:</b> @Html.TextBox("p")
                    <input type="submit" value="Ara" style="background-color:darkblue; color:white" class="btn btn-primary" />
                </td>
            </tr>
        </table>  
        
    </div>
}


<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Kitap Adı</th>
        <th>Kategori</th>
        <th>Yazar</th>
        <th>Basım Yılı</th>
        <th>Yayınevi</th>
        <th>Sayfa Sayısı</th>
        <th>Durum</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.ID</td>
            <td>@x.AD</td>
            <td>@x.TBL_KATEGORILER.AD</td>
            <td>@x.TBL_YAZARLAR.AD @x.TBL_YAZARLAR.SOYAD</td>
            <td>@x.BASIMYIL</td>
            <td>@x.YAYINEVI</td>
            <td>@x.SAYFA</td>
            <td>@x.DURUM</td>
            <td><a href="/Kitap/KitapSil/@x.ID" style="background-color:red; color:white" class="btn btn-danger">Sil</a></td>
            <td><a href="/Kitap/KitapGetir/@x.ID" style="background-color:darkorange; color:white" class="btn btn-warning">Güncelle</a></td>
        </tr>
    }
</table>
<a href="/Kitap/KitapEkle/" style="background-color:dodgerblue; color:white" class="btn btn-primary">Yeni Kitap Ekle</a>

MvcKutuphaneProje/Views/Kitap/KitapEkle.cshtml
@model MvcKutuphaneProje.Models.Entity.TBL_KITAPLAR
@{
    ViewBag.Title = "KitapEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div style="margin-bottom:15px; margin-top:15px">
        <label>Kitap Adı</label>
        @Html.TextBoxFor(k => k.AD, new { @class = "Form-Control" })
    </div>
    <div style="margin-bottom:15px">
        <label>Kategori</label>
        @Html.DropDownListFor(k => k.TBL_KATEGORILER.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        <label>Yazar</label>
        @Html.DropDownListFor(k => k.TBL_YAZARLAR.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        <label>Basım Yılı</label>
        @Html.TextBoxFor(k => k.BASIMYIL, new { @class = "Form-Control" })
    </div>
    <div style="margin-bottom:15px">
        <label>Yayınevi</label>
        @Html.TextBoxFor(k => k.YAYINEVI, new { @class = "Form-Control" })
    </div>
    <div style="margin-bottom:15px">
        <label>Sayfa</label>
        @Html.TextBoxFor(k => k.SAYFA, new { @class = "Form-Control" })
    </div>
    <button class="btn btn-success" style="background-color:green; color:white" >Kaydet</button>
    <a href="/Kitap/Index/" style="background-color:red; color:white" class="btn btn-danger">İptal</a>
    <input type="hidden" name="DURUM" value="True" />
</form>

MvcKutuphaneProje/Views/Kitap/KitapGetir.cshtml
@model MvcKutuphaneProje.Models.Entity.TBL_KITAPLAR
@{
    ViewBag.Title = "KitapGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}


@using (Html.BeginForm("KitapGuncelle", "Kitap", FormMethod.Post))
{
    <div style="margin-top:15px; margin-bottom:15px">
        <label>Kitap ID</label>
        @Html.TextBoxFor(x => x.ID, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:15px; margin-bottom:15px">
        <label>Kitap Adı</label>
        @Html.TextBoxFor(x => x.AD, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px; margin-bottom:15px">
        <label>Kategori</label>
        @Html.DropDownListFor(x => x.TBL_KATEGORILER.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px; margin-bottom:15px">
        <label>Yazar</label>
        @Html.DropDownListFor(k => k.TBL_YAZARLAR.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px; margin-bottom:15px">
        <label>Basım Yılı</label>
        @Html.TextBoxFor(x => x.BASIMYIL, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px; margin-bottom:15px">
        <label>Yayınevi</label>
        @Html.TextBoxFor(x => x.YAYINEVI, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px; margin-bottom:15px">
        <label>Sayfa</label>
        @Html.TextBoxFor(x => x.SAYFA, new { @class = "form-control" })
    </div>
    <button class="btn btn-warning" style="background-color:orangered; color:white" >Güncelle</button>
    <a href="/Kitap/Index/" style="background-color:red; color:white"  class="btn btn-danger">İptal</a>
}